const texts = {
  en: {
    home: "Home",
    projects: "Projects",
    contacts: "Contacts",
    name: 'Mikhail Goloveshkin',
    profession: 'is a front-end developer',
    contactButton: 'Contact me',
    madeBy: 'Made by TearsOprah',
    aboutMe: '',
    linkToProjects: 'View all',
    tagline: 'Adventures in Code: My Journey in Web Development',
    media: 'Media',
    contactsMessage: 'Don\'t hesitate to contact me regarding collaboration, I am open to full-time or project-based work opportunities.',
    messageMeHere: 'Message me here',
    skills: 'Skills',
  },
  ru: {
    home: "Главная",
    projects: "Проекты",
    contacts: "Контакты",
    name: 'Михаил Головешкин',
    profession: 'front-end разработчик',
    contactButton: 'Связаться со мной',
    madeBy: 'Выполнил TearsOprah',
    aboutMe: '',
    linkToProjects: 'Посмотреть все',
    tagline: 'Приключения в коде: мое путешествие в веб-разработке',
    media: 'Медиа',
    contactsMessage: 'Не стесняйтесь написать мне по поводу сотрудничества, я рассмотрю любые предложения о фулл-тайм либо попроектной работе.',
    messageMeHere: 'Напишите мне тут',
    skills: 'Навыки',
  },
}

export default texts;
